# Generated by Django 5.0.6 on 2024-06-18 08:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_alter_person_profileid'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='shared_to',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='shared_from', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='person',
            name='profileId',
            field=models.CharField(default='732272d8-5a98-4d0e-aa97-1aadb44317d3', max_length=255),
        ),
    ]
